### ISSUE TITLE
타이틀에서 메인으로 넘어가는 때의 잔상버그

### ISSUE THREAD

**Issue by jhj04** [jhj04/Snake_Game#15]
타이틀 화면에서 메인으로 넘어가는 때에 잔상(뒤쪽으로 타이틀 화면 글자의 일부가 보임)이 발생하는데 어떤 식으로 수정해야할 지 확인해주시면 감사하겠습니다!

**Comment by SeHyun-Kim04** [comment]
기존 Game Map에서는 사용한 부분에 다시 글자를 덮어씌우다 보니, 잔상(기존의 글자)이 남지 않았습니다.
하지만, 타이틀에서 나타나는 글자들은 다시 덮어씌우는 글자가 없다보니, 잔상이 남는것으로 확인됩니다.

따라서, 작성해주신 소스코드에서 메인으로 넘어가기전에 ```clear();```를 추가하시면 문제없이 작동할 것 같습니다.

**Comment by jhj04** [comment]
감사합니다!

**Comment by SeHyun-Kim04** [comment]
오류 수정후 Pull Request 갱신해주시면 다시 확인해보겠습니다
