### ISSUE TITLE
게이트 버그

### ISSUE THREAD

**Issue by seennothing** [jhj04/Snake_Game#5]
원래 GateMap.cpp의 CreateGate 메서드는 다음 과 같습니다. 반대편 벽뿐말 아니라 인접한 벽이나 같은 벽에 게이트를 생성했는데 그럴 때 버그다 생깁니다. 문제되는 부분이 Snake.cpp의 move 메서드 안에 lastDirection이 저장이 잘 안 되는 것 같습니다. 확인 부탁드립니다

void GameMap::createGate() {

    int width = getWidth();
    int height = getHeight();

    srand (time(NULL));
    int gate1, gate2;
    int x1, x2, y1, y2;

    do{
        gate1 = rand() % (width * 2 + height * 2 - 16) + 2;
        gate2 = rand() % (width* 2 + height * 2 - 16) + 2;

        if (gate1 < width - 2) y1 = 0, x1 = gate1;
        else if (gate1 < width + height - 6) y1 = gate1 - height + 4, x1 = width - 1;
        else if (gate1 < 2 * width + height - 10) y1 = height - 1, x1 = gate1 - width - height + 8;
        else y1 = gate1 - 2 * height - width + 12, x1 = 0;
    
        if (gate2 < width - 2) y2 = 0, x2 = gate2 ;
        else if (gate2 < width + height - 6) y2 = gate2 - height + 2, x2 = width - 1;
        else if (gate2 < 2 * width + height - 10) y2 = height - 1, x2 = gate2 - width - height + 8;
        else y2 = gate2 - 2 * height - width + 12, x2 = 0;
    } while ((x1 == x2 && y1 == y2) || (abs(x1 - x2) + abs(y1 - y2)) < 10);

    gates[0] = x1;
    gates[1] = y1;
    gates[2] = x2;
    gates[3] = y2;
}

**Comment by SeHyun-Kim04** [comment]
소스코드가 일부만 업로드 되어있어서 정확한 판단은 불가능하지만, 아마 게이트 이동후 뱀의 "lastDirection"을 따로 지정해 주지 않아서 발생하는 문제인 것 같습니다.

게이트를 타고 이동한 후, "lastDirection"의 위치를 반전으로 (좌 > 우, 우 < 좌)로 변경해 주는 코드를 추가하시면 문제가 해결될 것 같습니다.

다만, 이는 소스코드의 일부만 보고 추측한 내용이므로, 다른 문제였을 수도 있다는 점 미리 알려드립니다.

**Comment by SeHyun-Kim04** [comment]
[게이트 추가](https://github.com/jhj04/Snake_Game/pull/8) Pull Request에서 문제가 해결된 것으로 보입니다.
혹시 여전히 문제가 지속된다면 Issue를 다시 열어주세요.
